POST http://localhost:3001/api/patients/
Content-Type: application/json

{
    "name": "uusiPotilas",
    "dateOfBirth": "1986-07-09",
    "ssn": "090786-122Y",
    "gender": "male",
    "occupation": "truck driver"
}